import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/card';
import { Dumbbell, Target, BrainCircuit, HeartPulse } from 'lucide-react';
import DashboardChart from './dashboard-chart';

export default function DashboardPage() {
  return (
    <div className="p-4 md:p-8">
      <h1 className="font-headline text-3xl font-bold text-foreground md:text-4xl mb-6">
        Welcome Back, User!
      </h1>
      <p className="text-muted-foreground mb-8">Here's a summary of your health and fitness journey.</p>
      
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Current BMI</CardTitle>
            <Target className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">22.5</div>
            <p className="text-xs text-muted-foreground">Healthy range</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Basal Metabolic Rate (BMR)</CardTitle>
            <HeartPulse className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">1,850</div>
            <p className="text-xs text-muted-foreground">calories/day at rest</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Last Workout</CardTitle>
            <Dumbbell className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">Upper Body</div>
            <p className="text-xs text-muted-foreground">45 minutes</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Next Meal Plan</CardTitle>
            <BrainCircuit className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">High Protein</div>
            <p className="text-xs text-muted-foreground">Generated by AI Coach</p>
          </CardContent>
        </Card>
      </div>

      <div className="mt-8">
        <Card>
          <CardHeader>
            <CardTitle>Weekly Workout Progress</CardTitle>
          </CardHeader>
          <CardContent>
            <DashboardChart />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
